trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'  # This will install Node.js 20.x
  displayName: 'Set up Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build-css
  displayName: 'Build CSS'

- script: |
    npx tsx src/tests/unit_test.ts
  displayName: 'Run src/tests/unit_test.ts'
  continueOnError: false
