# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: UseNode@1
  inputs:
    version: '16.x'

- script: npm install
  displayName: 'npm install'

- script: |
    npx tsx src/tests/edit_incident_report.ts
  displayName: 'Run src/tests/edit_incident_report.ts with tsx'
  continueOnError: false
