name: PR Webhook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"A new commit has been pushed to the main branch!\"}" \
            "https://discord.com/api/webhooks/1275330311299010570/uOxNQcfMJqPXQAaf4T7cynDsA0wAwcPh9YFQPTFWaIN7MY6m39UBpNi3osbv9cAF_wEG"
